import { FormEvent, useEffect, useState } from "react";
import { BookOpen, Boxes, CheckCircle2, ChevronRight, CircleUserRound, Database, Download, FileText, Home, Info, LogIn, LogOut, Menu, Pencil, Plus, Printer, ShieldCheck, Trash2, UserRound, X } from "lucide-react";

type User = { id: number; username: string; email: string; role: "ADMIN" | "USER" };
type Student = { id: number; student_id: string; name: string; email: string; course: string; year: number; department: string };
type StudentDraft = Omit<Student, "id">;
type Page = "home" | "dashboard" | "students" | "assets" | "matrix" | "report" | "about";
const API = "http://127.0.0.1:8001";
const assets = [
  ["Web Tier", "Presents the application interface to users.", "Cross-site scripting and exposed client data.", "TypeScript UI, input escaping, and limited CORS."],
  ["Application Tier", "Processes business rules and security decisions.", "Broken authorization or unsafe input handling.", "FastAPI validation, JWT checks, and role authorization."],
  ["Database", "Stores users and student records.", "Unauthorized queries or data loss.", "SQLAlchemy ORM, least-privilege endpoints, and local access."],
  ["User Credentials", "Verifies identity before access is granted.", "Password theft or plaintext storage.", "bcrypt hashing, JWT expiry, and environment secrets."],
  ["Student Data", "Provides the records managed by the application.", "Disclosure, tampering, or invalid records.", "Protected APIs, validation, and ADMIN-only mutations."],
];
const matrix = [["Infrastructure", "Physical hosting, availability", "Application deployment and configuration"], ["Operating System", "Host patching and hardening", "Secure local runtime and dependencies"], ["Network Security", "Network perimeter and transport", "CORS policy and secure API access"], ["Application Security", "Platform security capabilities", "Validation, authorization, and secure code"], ["Authentication", "Identity service availability", "JWT flow, roles, and bcrypt passwords"], ["Database Security", "Managed database platform", "Schema, ORM queries, and access rules"], ["Data Protection", "Underlying storage resilience", "Minimize exposure and protect records"], ["Security Updates", "Provider infrastructure updates", "Application and dependency updates"]];

async function request(path: string, options: RequestInit = {}, token?: string) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } });
  const data = response.status === 204 ? null : await response.json();
  if (!response.ok) throw new Error(data?.detail || "Request failed");
  return data;
}

export default function App() {
  const [page, setPage] = useState<Page>("home");
  const [user, setUser] = useState<User | null>(() => JSON.parse(localStorage.getItem("user") || "null"));
  const [token, setToken] = useState(() => localStorage.getItem("token") || "");
  const [loginOpen, setLoginOpen] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const logout = () => { localStorage.clear(); setUser(null); setToken(""); setPage("home"); };
  const navigate = (next: Page) => { if ((next === "dashboard" || next === "students") && !user) { setLoginOpen(true); return; } setPage(next); setMenuOpen(false); };
  return <div className="min-h-screen bg-[#f3f7f7]">
    <header className="border-b border-[#d6e6e3] bg-white/90 backdrop-blur sticky top-0 z-20"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
      <button onClick={() => navigate("home")} className="flex items-center gap-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#102a43] text-[#a7e8dc]"><ShieldCheck size={23}/></span><span><b className="block text-sm tracking-wide text-[#102a43]">SECURE 3-TIER</b><small className="text-xs text-[#52727a]">Cloud Security PBL · Unit 1</small></span></button>
      <button className="md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X/> : <Menu/>}</button>
      <nav className={`${menuOpen ? "absolute left-0 right-0 top-full flex" : "hidden"} flex-col gap-1 border-b border-[#d6e6e3] bg-white p-4 md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0`}>
        <NavButton icon={<Home size={16}/>} label="Home" active={page === "home"} onClick={() => navigate("home")}/><NavButton icon={<CircleUserRound size={16}/>} label="Dashboard" active={page === "dashboard"} onClick={() => navigate("dashboard")}/><NavButton icon={<UserRound size={16}/>} label="Students" active={page === "students"} onClick={() => navigate("students")}/><NavButton icon={<Boxes size={16}/>} label="Assets" active={page === "assets"} onClick={() => navigate("assets")}/><NavButton icon={<BookOpen size={16}/>} label="Matrix" active={page === "matrix"} onClick={() => navigate("matrix")}/><NavButton icon={<FileText size={16}/>} label="Report" active={page === "report"} onClick={() => navigate("report")}/><NavButton icon={<Info size={16}/>} label="About" active={page === "about"} onClick={() => navigate("about")}/>
        {user ? <button onClick={logout} className="mt-2 flex items-center justify-center gap-2 rounded-lg border border-[#cbdedb] px-3 py-2 text-sm font-bold text-[#b14e45] md:mt-0"><LogOut size={16}/> Logout</button> : <button onClick={() => setLoginOpen(true)} className="mt-2 flex items-center justify-center gap-2 rounded-lg bg-[#f07c50] px-4 py-2 text-sm font-bold text-white md:mt-0"><LogIn size={16}/> Login</button>}
      </nav></div></header>
    <main className="mx-auto max-w-7xl px-5 py-10">{page === "home" && <HomePage onLogin={() => setLoginOpen(true)} onExplore={() => navigate("dashboard")}/>} {page === "dashboard" && <Dashboard user={user!}/>} {page === "students" && <Students token={token} isAdmin={user?.role === "ADMIN"}/>} {page === "assets" && <Assets/>} {page === "matrix" && <Matrix/>} {page === "report" && <SSHReport/>} {page === "about" && <About/>}</main>
    {loginOpen && <Login onClose={() => setLoginOpen(false)} onSuccess={(newToken, newUser) => { setToken(newToken); setUser(newUser); localStorage.setItem("token", newToken); localStorage.setItem("user", JSON.stringify(newUser)); setLoginOpen(false); setPage("dashboard"); }}/>} 
  </div>;
}
function NavButton({ icon, label, active, onClick }: { icon: React.ReactNode; label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-bold ${active ? "bg-[#e5f6f1] text-[#087f73]" : "text-[#52727a] hover:bg-[#f3f7f7]"}`}>{icon}{label}</button>; }
function HomePage({ onLogin, onExplore }: { onLogin: () => void; onExplore: () => void }) { return <><section className="relative overflow-hidden rounded-3xl bg-[#102a43] px-7 py-16 text-white md:px-16"><div className="absolute -right-24 -top-32 h-80 w-80 rounded-full border-[36px] border-[#1e6170]/60"/><div className="relative max-w-3xl"><p className="mb-5 text-sm font-bold uppercase tracking-[.22em] text-[#a7e8dc]">A practical security foundation</p><h1 className="max-w-2xl text-4xl font-black leading-tight md:text-6xl">Secure 3-Tier Web Application</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#c7dcda]">A focused Unit 1 project showing how a web tier, application tier, and database tier work together with security controls at every boundary.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={onLogin} className="flex items-center gap-2 rounded-lg bg-[#f07c50] px-5 py-3 font-bold text-white">Login to workspace <ChevronRight size={18}/></button><button onClick={onExplore} className="rounded-lg border border-[#6ea9a1] px-5 py-3 font-bold text-[#d8f5ef]">Explore architecture</button></div></div></section><section className="py-12"><div className="mb-6 flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-[#f07c50]">Architecture</p><h2 className="mt-2 text-2xl font-black text-[#102a43]">Three layers. One security story.</h2></div><span className="hidden text-sm text-[#52727a] md:block">Local-first · easy to inspect</span></div><div className="grid gap-4 md:grid-cols-3">{[["01", "WEB TIER", "React + TypeScript", "User-facing interface"], ["02", "APP TIER", "FastAPI + JWT", "Rules and authorization"], ["03", "DB TIER", "SQLite + SQLAlchemy", "Structured records"]].map(([num, title, tech, copy]) => <div key={title} className="border-t-4 border-[#4cb8a9] bg-white p-6 shadow-sm"><span className="text-sm font-black text-[#f07c50]">{num}</span><h3 className="mt-7 text-xl font-black text-[#102a43]">{title}</h3><p className="mt-2 font-bold text-[#087f73]">{tech}</p><p className="mt-4 text-sm text-[#52727a]">{copy}</p></div>)}</div></section></>; }
function Login({ onClose, onSuccess }: { onClose: () => void; onSuccess: (token: string, user: User) => void }) { const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const data = await request("/auth/login", { method: "POST", body: JSON.stringify({ username, password }) }); onSuccess(data.access_token, data.user); } catch (err) { setError((err as Error).message); } finally { setLoading(false); } }; return <div className="fixed inset-0 z-30 grid place-items-center bg-[#102a43]/60 p-5"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-sm font-bold uppercase tracking-widest text-[#f07c50]">Protected access</p><h2 className="mt-2 text-2xl font-black">Sign in</h2></div><button type="button" onClick={onClose} aria-label="Close"><X/></button></div><label className="mt-7 block text-sm font-bold">Username<input required autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} className="mt-2 w-full rounded-lg border border-[#cbdedb] px-3 py-3 outline-none focus:border-[#087f73]"/></label><label className="mt-4 block text-sm font-bold">Password<input required autoComplete="current-password" type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-[#cbdedb] px-3 py-3 outline-none focus:border-[#087f73]"/></label>{error && <p className="mt-4 rounded-lg bg-[#fff0ed] p-3 text-sm font-bold text-[#b14e45]">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-lg bg-[#102a43] py-3 font-bold text-white disabled:opacity-60">{loading ? "Checking..." : "Continue securely"}</button></form></div>; }
function Dashboard({ user }: { user: User }) { return <PageIntro eyebrow="Overview" title="Security dashboard" copy="A quick view of your authenticated workspace and the controls protecting it." ><div className="grid gap-5 md:grid-cols-3"><InfoCard label="Signed in as" value={user.username} icon={<UserRound/>}/><InfoCard label="Access role" value={user.role} icon={<ShieldCheck/>}/><InfoCard label="Security status" value="Protected" icon={<CheckCircle2/>} green/></div><div className="mt-6 border border-[#cbdedb] bg-white p-6"><h3 className="font-black">Active controls</h3><div className="mt-4 grid gap-3 text-sm text-[#52727a] md:grid-cols-2"><Control text="JWT token required for protected APIs"/><Control text="bcrypt protects stored password hashes"/><Control text="ADMIN role controls student changes"/><Control text="Pydantic validates submitted records"/></div></div></PageIntro>; }
function InfoCard({ label, value, icon, green }: { label: string; value: string; icon: React.ReactNode; green?: boolean }) { return <div className="bg-white p-6 shadow-sm"><div className={`mb-7 grid h-10 w-10 place-items-center rounded-lg ${green ? "bg-[#e5f6f1] text-[#087f73]" : "bg-[#fff0ed] text-[#f07c50]"}`}>{icon}</div><p className="text-sm text-[#52727a]">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>; }
function Control({ text }: { text: string }) { return <p className="flex items-center gap-2"><CheckCircle2 size={17} className="text-[#087f73]"/>{text}</p>; }
function PageIntro({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children: React.ReactNode }) { return <><div className="mb-8"><p className="text-sm font-bold uppercase tracking-widest text-[#f07c50]">{eyebrow}</p><h1 className="mt-2 text-4xl font-black text-[#102a43]">{title}</h1><p className="mt-3 max-w-2xl text-[#52727a]">{copy}</p></div>{children}</>; }
function Students({ token, isAdmin }: { token: string; isAdmin: boolean }) { const [students, setStudents] = useState<Student[]>([]); const [editing, setEditing] = useState<Student | null>(null); const [showForm, setShowForm] = useState(false); const [error, setError] = useState(""); const load = () => request("/students", {}, token).then(setStudents).catch(err => setError(err.message)); useEffect(() => { load(); }, [token]); const save = async (data: StudentDraft) => { try { await request(editing ? `/students/${editing.id}` : "/students", { method: editing ? "PUT" : "POST", body: JSON.stringify(data) }, token); setShowForm(false); setEditing(null); load(); } catch (err) { setError((err as Error).message); } }; const remove = async (id: number) => { if (confirm("Delete this student record?")) { await request(`/students/${id}`, { method: "DELETE" }, token); load(); } }; return <PageIntro eyebrow="Protected records" title="Student management" copy={isAdmin ? "You have administrator access. Add, edit, or delete student records." : "Read-only access. Administrator permission is required to change records."}><div className="mb-4 flex justify-end">{isAdmin && <button onClick={() => { setEditing(null); setShowForm(true); }} className="flex items-center gap-2 rounded-lg bg-[#087f73] px-4 py-2 font-bold text-white"><Plus size={17}/> Add student</button>}</div>{error && <p className="mb-4 rounded-lg bg-[#fff0ed] p-3 text-sm font-bold text-[#b14e45]">{error}</p>}<div className="overflow-x-auto border border-[#cbdedb] bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#e5f6f1] text-xs uppercase tracking-wide text-[#52727a]"><tr>{["Student", "Email", "Course", "Year", "Department", "Access"].map(h => <th className="px-5 py-4" key={h}>{h}</th>)}</tr></thead><tbody>{students.map(student => <tr className="border-t border-[#e5efed]" key={student.id}><td className="px-5 py-4"><b>{student.name}</b><small className="block text-[#52727a]">{student.student_id}</small></td><td className="px-5 py-4">{student.email}</td><td className="px-5 py-4">{student.course}</td><td className="px-5 py-4">Year {student.year}</td><td className="px-5 py-4">{student.department}</td><td className="px-5 py-4">{isAdmin ? <span className="flex gap-2"><button onClick={() => { setEditing(student); setShowForm(true); }} aria-label="Edit student" className="rounded p-1 text-[#087f73] hover:bg-[#e5f6f1]"><Pencil size={17}/></button><button onClick={() => remove(student.id)} aria-label="Delete student" className="rounded p-1 text-[#b14e45] hover:bg-[#fff0ed]"><Trash2 size={17}/></button></span> : <span className="text-[#52727a]">View only</span>}</td></tr>)}</tbody></table></div>{showForm && <StudentForm initial={editing} onCancel={() => setShowForm(false)} onSave={save}/>}</PageIntro>; }
function StudentForm({ initial, onCancel, onSave }: { initial: Student | null; onCancel: () => void; onSave: (data: StudentDraft) => void }) { const [form, setForm] = useState<StudentDraft>(initial ? { student_id: initial.student_id, name: initial.name, email: initial.email, course: initial.course, year: initial.year, department: initial.department } : { student_id: "", name: "", email: "", course: "", year: 1, department: "" }); const update = (key: keyof typeof form, value: string) => setForm({ ...form, [key]: key === "year" ? Number(value) : value }); return <div className="fixed inset-0 z-30 grid place-items-center bg-[#102a43]/60 p-5"><form onSubmit={e => { e.preventDefault(); onSave(form); }} className="w-full max-w-2xl rounded-2xl bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-black">{initial ? "Edit student" : "Add student"}</h2><button type="button" onClick={onCancel}><X/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{(["student_id", "name", "email", "course", "year", "department"] as const).map(key => <label className="text-sm font-bold capitalize" key={key}>{key.replace("_", " ")}<input required value={form[key]} onChange={e => update(key, e.target.value)} type={key === "year" ? "number" : key === "email" ? "email" : "text"} className="mt-2 w-full rounded-lg border border-[#cbdedb] px-3 py-3"/></label>)}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-lg border border-[#cbdedb] px-4 py-2 font-bold">Cancel</button><button className="rounded-lg bg-[#087f73] px-4 py-2 font-bold text-white">Save record</button></div></form></div>; }
function Assets() { return <PageIntro eyebrow="Security inventory" title="Asset inventory" copy="The five assets in scope for this Unit 1 application and the controls assigned to each one."><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{assets.map(([name, purpose, concern, control]) => <article className="border border-[#cbdedb] bg-white p-6" key={name}><div className="flex items-center gap-3"><Database size={19} className="text-[#087f73]"/><h2 className="font-black">{name}</h2></div><dl className="mt-6 space-y-4 text-sm"><div><dt className="font-bold text-[#52727a]">Purpose</dt><dd className="mt-1">{purpose}</dd></div><div><dt className="font-bold text-[#b14e45]">Security concern</dt><dd className="mt-1">{concern}</dd></div><div><dt className="font-bold text-[#087f73]">Security control</dt><dd className="mt-1">{control}</dd></div></dl></article>)}</div></PageIntro>; }
function Matrix() { return <PageIntro eyebrow="Shared responsibility" title="Responsibility matrix" copy="Security is shared: the provider supports the underlying environment while the customer and developer secure the application and its data."><div className="overflow-x-auto border border-[#cbdedb] bg-white"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-[#102a43] text-white"><tr><th className="px-5 py-4">Area</th><th className="px-5 py-4">Cloud provider responsibility</th><th className="px-5 py-4">Customer / developer responsibility</th></tr></thead><tbody>{matrix.map(row => <tr className="border-t border-[#e5efed]" key={row[0]}>{row.map((cell, i) => <td className={`px-5 py-4 ${i === 0 ? "font-black text-[#102a43]" : "text-[#52727a]"}`} key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></PageIntro>; }
function SSHReport() {
  const [logs, setLogs] = useState("");
  const failedLines = logs.split(/\r?\n/).filter(line => /failed password|invalid user/i.test(line));
  const ips = [...new Set(failedLines.flatMap(line => line.match(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g) || []))];
  const usernames = [...new Set(failedLines.map(line => line.match(/(?:invalid user|for)\s+([^\s]+?)(?:\s+from|\s+port|\s*$)/i)?.[1]).filter(Boolean) as string[])];
  const firstAttempt = failedLines[0]?.match(/^\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}/)?.[0] || (failedLines.length ? "Timestamp not detected in pasted lines" : "Not available");
  const assessment = failedLines.length >= 3 || ips.length >= 2 ? "Likely automated: repeated failed attempts or multiple source IPs were detected." : failedLines.length ? "Inconclusive: there are failed attempts, but more evidence is needed to classify them." : "Not available until SSH log output is pasted.";
  const reportText = `SSH Login Attempt Report\n\nEvidence source: journalctl -u sshd | grep -i failed\nFailed attempts: ${failedLines.length}\nFirst attempt: ${firstAttempt}\nSource IPs: ${ips.length ? ips.join(", ") : "None detected"}\nAttempted usernames: ${usernames.length ? usernames.join(", ") : "None detected"}\nAutomation assessment: ${assessment}\n\nNote: This report reflects only the log text pasted into the tool.`;
  const download = () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([reportText], { type: "text/plain" })); link.download = "ssh-login-attempt-report.txt"; link.click(); URL.revokeObjectURL(link.href); };
  return <PageIntro eyebrow="Unit 1 evidence" title="SSH login attempt report" copy="Paste the output collected from your Linux instance. The browser analyzes only the evidence you provide and does not connect to AWS or expose your server IP."><div className="grid gap-6 lg:grid-cols-[1fr_380px]"><div><label className="block text-sm font-bold text-[#102a43]">SSH log output<textarea value={logs} onChange={event => setLogs(event.target.value)} placeholder={'Paste output from:\njournalctl -u sshd | grep -i "failed"'} className="mt-2 min-h-[260px] w-full rounded-lg border border-[#cbdedb] bg-white p-4 font-mono text-sm outline-none focus:border-[#087f73]"/></label><div className="mt-4 flex flex-wrap gap-3"><button onClick={download} disabled={!logs.trim()} className="flex items-center gap-2 rounded-lg bg-[#087f73] px-4 py-2 font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Download size={17}/> Download report</button><button onClick={() => window.print()} disabled={!logs.trim()} className="flex items-center gap-2 rounded-lg border border-[#cbdedb] bg-white px-4 py-2 font-bold text-[#102a43] disabled:cursor-not-allowed disabled:opacity-40"><Printer size={17}/> Print / save PDF</button><button onClick={() => setLogs("")} className="rounded-lg px-4 py-2 font-bold text-[#b14e45]">Clear</button></div></div><div className="border border-[#cbdedb] bg-white p-6"><div className="flex items-center gap-2"><FileText size={19} className="text-[#f07c50]"/><h2 className="font-black">Report findings</h2></div><dl className="mt-6 space-y-5 text-sm"><div><dt className="text-[#52727a]">Failed attempts</dt><dd className="mt-1 text-2xl font-black text-[#102a43]">{failedLines.length}</dd></div><div><dt className="text-[#52727a]">Source IPs</dt><dd className="mt-1 font-bold">{ips.length ? ips.join(", ") : "None detected"}</dd></div><div><dt className="text-[#52727a]">Usernames attempted</dt><dd className="mt-1 font-bold">{usernames.length ? usernames.join(", ") : "None detected"}</dd></div><div><dt className="text-[#52727a]">First attempt</dt><dd className="mt-1 font-bold">{firstAttempt}</dd></div><div><dt className="text-[#52727a]">Automation assessment</dt><dd className="mt-1 leading-6">{assessment}</dd></div></dl></div></div></PageIntro>;
}
function About() { return <PageIntro eyebrow="Project brief" title="About this project" copy="A compact, inspectable implementation for a Cloud Security PBL assessment."><div className="grid gap-5 md:grid-cols-2"><div className="bg-white p-7"><h2 className="text-lg font-black">Project</h2><p className="mt-3 text-[#52727a]">Secure 3-Tier Web Application</p><h2 className="mt-7 text-lg font-black">Unit</h2><p className="mt-3 text-[#52727a]">Cloud Security · Unit 1</p><h2 className="mt-7 text-lg font-black">Objective</h2><p className="mt-3 text-[#52727a]">Demonstrate authentication, authorization, protected records, and shared responsibility across a simple three-tier design.</p></div><div className="bg-[#102a43] p-7 text-white"><h2 className="text-lg font-black">Tech stack</h2><ul className="mt-5 space-y-3 text-[#c7dcda]"><li>React + TypeScript + Tailwind CSS</li><li>FastAPI + JWT authentication</li><li>SQLite + SQLAlchemy ORM</li><li>bcrypt password hashing</li></ul></div></div></PageIntro>; }
